### ISSUE TITLE
The "Dump with files" option produces duplicate files and 

### ISSUE THREAD

**Issue by johann-petrak** [codalab/codabench#1393]
I have created a competition with input data, scoring programs from uploading a bundle file and there are also already test submissions. 

When I then try to download using the "Dump with files" option I see the following oddities/problems:

* The zip file that I get contains several files with the same name, in my case this is input_data-6224.zip feference_data-6224.zip and scoring_program-6224.zip which all occur twice in the zip file with identical names. 
* some of the reference*.zip files contain files which are definitely not from the project where I downloaded the dump from but from other projects I created (and deleted) previously
* I also seem to get different versions of the scoring program

What is going on here, should the dump not be restricted to those data/program files which are actually part of the project?

And if I upload a bundle that contains e.g. a target file or scorer and then remove the project, should those files and scorers not get removed with the project they belong to?

**Comment by Didayolo** [comment]
The dump is supposed to contain only the files related to the current state of the competition.

Can you please share the URL to the competition so we can investigate this?

**Comment by johann-petrak** [comment]
This is the one where I tried this: https://www.codabench.org/competitions/2618/?secret_key=74ac0264-1d23-4148-8f9a-dcdb66e08ab3

**Comment by johann-petrak** [comment]
I am not sure which file you have downloaded or which you are seeing as the user you used.

I see the following list (the last one I have created via the "Dump with files" option:
![dump01](https://github.com/codalab/codabench/assets/619106/b7b0f5dd-2598-4452-b0b5-f326cb5da2cd)

Sadly the name in the list does not indicate which option was used to create it, and the name in the list is not used as the name when downloading the file. When downloading the file, it gets saved as "GermEval_GERMS-DETECT1-Closed-2024-.zip"

Here is the content of this zip file: 
```
$ unzip -l GermEval_GERMS-DETECT1-Closed-2024-.zip 
Archive:  GermEval_GERMS-DETECT1-Closed-2024-.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     3458  2024-04-11 09:48   logo.png
      265  2024-04-11 09:48   terms.md
      542  2024-04-11 09:48   participation-12250.md
       22  2024-04-11 09:48   input_data-6223.zip
    40827  2024-04-11 09:48   reference_data-6223.zip
     6463  2024-04-11 09:48   scoring_program-6223.zip
       22  2024-04-11 09:48   input_data-6224.zip
      192  2024-04-11 09:48   reference_data-6224.zip
     6463  2024-04-11 09:48   scoring_program-6224.zip
       22  2024-04-11 09:48   input_data-6224.zip
      192  2024-04-11 09:48   reference_data-6224.zip
     6463  2024-04-11 09:48   scoring_program-6224.zip
     2619  2024-04-11 09:48   competition.yaml
---------                     -------
    67550                     13 files
```

As you can see there are two files called "reference_data-6224.zip" and other files which are present in the zip archive multiple times and lead to prompts when unzipping:

![dump02](https://github.com/codalab/codabench/assets/619106/6b8abc99-811f-48e1-bdd9-514892508ef2)

The part of the competition.yaml file you quoted actually shows that the file name reference_data-6224.zip is used
for two different tasks and these are included as two different files with the same name in the zip file. 
Note that originally, the competition.yaml file does NOT specify a zip file but a path, and the paths for task with index 1 and task with index 2 are different:

```
  - index: 1
    name: ST${subtask}-${track}
    is_public: true
    description: Subtask ${subtask}, ${track} Track
    reference_data: dev_phase/reference_data/
    scoring_program: scoring_program/
    input_data: input_data/
    # ingestion_program: ingestion_program/
  - index: 2
    name: ST${subtask}-${track}
    is_public: true
    description: Subtask ${subtask}, ${track} Track
    reference_data: comp_phase/reference_data/
    scoring_program: scoring_program/
    input_data: input_data/
    # ingestion_program: ingestion_program/
```

The confusion where I believed that the file comes from a different project was my mistake because in that version of the bundle I copy/pasted the wrong file into the reference data directory. 

So there is definitely the problem that when dump with files is used, files with identical names are used to archive different data from different subdirectories.

**Comment by ihsaan-ullah** [comment]
with the unzip command you are using, I `see reference_data-6224` two times 
<img width="401" alt="Screenshot 2024-04-11 at 4 21 11 PM" src="https://github.com/codalab/codabench/assets/13259262/256302b0-5c6b-46cf-91f2-cac18be4c78a">

but when you check the folder you can see just one file
<img width="419" alt="Screenshot 2024-04-11 at 4 21 55 PM" src="https://github.com/codalab/codabench/assets/13259262/9744f6ee-18ce-4407-a220-2397c4524683">


If a file with the same name already exists, normally it is overwritten.

**Comment by johann-petrak** [comment]
@ihsaan-ullah I do not understand what you mean: clearly the zip archive I download contains duplicate files. Most versions of zip when unzipping such an archive, will prompt before overriding a file with the same name, if there is no prompt this would be even worse! 
But the main thing here is that the files with identical names refer to different files in the original bundle and should definitely not have the same name! Why would anyone deliberately place two files with identical filenames into a zip archive? It does not make any sense to me.

**Comment by ihsaan-ullah** [comment]
I think now I see a problem.

To make things more clear. What do you expect?

From the competition, I see you have 3 pahses but they share the same task so there should be one set of {ingestion, scoring, input, reference}. But in your yaml file from the dump, I see 3 tasks(wrong) and 3 phases (right but one phase uses task 0 and other uses task 2, task 1 is not used)

**Comment by johann-petrak** [comment]
> When I unzip both reference data (6223 and 6224) they both have different content but the file name is same, this is also weird because the task is same for all the phases

This is not weird since in the bundle I originally uploaded, the data comes from different subdirectories in the different phases. The original competition.yaml file uploaded to create this project contained something like this:

```
phases:
  - name: Setup Phase
    description: 'Internal phase for developing and debugging the competition code'
    start: 2024-03-01
    end: 2024-04-11
    max_submissions_per_day: 1000
    max_submissions: 1000
    execution_time_limit: 60
    solutions: []
    tasks:
      - 0
  - name: Trial Phase
    description: 'Trial phase: Try everything out with a preliminary small training and test set'
    start: 2024-04-12
    end: 2024-04-30
    max_submissions_per_day: 20
    max_submissions: 20
    execution_time_limit: 60
    solutions: []
    # public_data: public_data
    # starting_kit: starting_kit
    tasks:
      - 0
  - name: Development Phase
    description: 'Development phase: Try everything out, train on training data, evaluate on dev data.'
    start: 2024-05-01
    end: 2024-06-06
    max_submissions_per_day: 1000
    max_submissions: 1000
    execution_time_limit: 60
    solutions: []
    # public_data: public_data
    # starting_kit: starting_kit
    tasks:
      - 1
```

So it may be important to state the the zip files included here are not MY zip files but something the system has created after I uploaded the bundle with a completely different directory structure.
