### ISSUE TITLE
Configure Redis to Only Be Accessible Locally in Docker (Avoid Malware Attack)

### ISSUE THREAD

**Issue by itstyren** [codalab/codabench#1637]
## Description:
First, thank you for this amazing project. I'm trying to deploy it on my own server, following the provided instructions. However, I am struggling with how to configure Redis to be accessible only from localhost to prevent external access. The reason I want to do this is that I encountered a malware attack because port 6379 was publicly accessible.

## Procedure
I have made the following changes:
Edited the redis.conf file to bind Redis to localhost:

1. Edited the redis.conf file to bind Redis to localhost:
```base
bind 127.0.0.1 -::1
```
2. Updated my `docker-compose.yml` file:
```yaml
redis:
  image: redis
  ports:
    - 6379:6379
  restart: unless-stopped
  logging:
    options:
      max-size: "20m"
      max-file: "5"
  volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf 
  command: ["redis-server", "/usr/local/etc/redis/redis.conf"] 
```
3. Ran the following commands to restart my Docker containers:
```bash
docker-compose down
docker-compose up -d
```

## Issue
After applying these changes, I encountered the following error in my Django logs:
```bash
[INFO] ('172.18.0.11', 58186) - "WebSocket /submission_output/" [accepted]
[ERROR] Exception in ASGI application
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 157, in run_asgi
  result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
  return await self.app(scope, receive, send)
```
## Question
How can I ensure Redis is only accessible from localhost in Docker setup? 

Any guidance or assistance would be greatly appreciated!

**Comment by ObadaS** [comment]
Hello,
As an alternative, you can make a small edit in the `docker-compose.yml` to only allow local connection to `redis` 

```yaml
  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
    restart: unless-stopped
    logging:
      options:
        max-size: "20m"
        max-file: "5"
```

With this method, you won't need any other changes to make it work.
I hope this solution prevents any other attacks for you !
