### ISSUE TITLE
Program directory missing metadata, assuming it's going to be handled by ingestion program so move it to output

### ISSUE THREAD

**Issue by xy3xy3** [codalab/codabench#1805]
I have created a competition bundle containing the following files:

- **competition.yaml** (competition configuration)
- **scoring_program/scoring_program.py** (scoring script)
- **scoring_program/metadata.yaml** (scoring program command configuration)

However, during execution, I receive the following error message:
```
[2025-04-02 06:44:07,720: INFO/ForkPoolWorker-2] Running scoring program, and then ingestion program
[2025-04-02 06:44:07,720: INFO/ForkPoolWorker-2] Program directory missing metadata, assuming it's going to be handled by ingestion program so move it to output
[2025-04-02 06:44:07,720: INFO/ForkPoolWorker-2] Updating submission @ http://django:8000/api/submissions/86/ with data = {'status': 'Failed', 'status_details': "Program directory missing 'metadata.yaml/metadata'", 'secret': '74acf53d-e75e-4635-9d26-94da7bcd22be'}
[2025-04-02 06:44:07,767: INFO/ForkPoolWorker-2] Submission updated successfully!
[2025-04-02 06:44:07,767: INFO/ForkPoolWorker-2] CODALAB_IGNORE_CLEANUP_STEP mode enabled, ignoring clean up of: /codabench/tmpb8sifq1n
[2025-04-02 06:44:07,767: INFO/ForkPoolWorker-2] Task compute_worker_run[151b6b0c-9b5e-459d-8c4b-21be8e97dc65] succeeded in 3.5456645549857058s: None
```
This indicates that the system cannot find the required metadata file in the scoring_program directory, so it treats the directory as if it were an ingestion program and moves it to the output directory.

### Environment
- Docker image: `codalab/codalab-legacy:py39`
- Bundle version: 2 (CodaBench bundle)

### Steps to Reproduce
1. Package and upload the following bundle structure:
    - **MyTest/competition.yaml**
    - **MyTest/scoring_program/scoring_program.py**
    - **MyTest/scoring_program/metadata.yaml**
2. A prediction.zip is submitted by the user (containing the file prediction.json).
3. When the system runs the scoring program, the log shows the error mentioned above, leading to a failure of the submission.

### File Contents
File: MyTest\competition.yaml
```yaml
title: "直接给分" # 比赛名
version: 2 # 1 指是 CodaLab bundle，2 指 CodaBench bundle，区别是有些 competition.yaml 字段不兼容
description: "Test" # 比赛描述
image: "logo.png" # 比赛 logo.png
registration_auto_approve: True  # do not require approval from organizers to join
docker_image: codalab/codalab-legacy:py39 # the Docker image in which submissions are run，用此 default 即可
enable_detailed_results: True # 不明，可以 default

# Documentation web pages
terms: pages/terms.md # 必须有一个 terms
pages: []  # 暂时不添加额外页面

# Definition of the tasks
tasks:
- index: 0
  name: "任务" # e.g., Development Task
  description: "描述" # 描述
  is_public: true   # 公开可见
  input_data: "" # e.g., feedback_phase/input_data, 此处及下列路径需要填写所上传 bundle 里的路径，而非所生成 Docker 中的
  reference_data: "" # e.g., feedback_phase/reference_data
  scoring_program: scoring_program/
  ingestion_program: "" # e.g., ingestion_program

# Sample code submission
solutions: [] # 可以为空

phases:
- index: 0
  name: "开发阶段"             # phase 标题
  description: "开发阶段描述"      # 描述
  start: 1-1-2024   # Month / Day / Year
  end: 1-30-2029    # end 结束时间可以缺失，表示永远可提交
  max_submissions_per_day: 5    # 最大似乎是 100？
  max_submissions: 100          # 最大似乎是 10000？
  execution_time_limit: 600     # 每次提交允许的最长运行时间，超过这个时间将显示 run time exceed
  tasks:            # 与该 phase 关联的 tasks
  - 0
  solutions: []
  starting_kit: "" # e.g., starting_kit, 可能会显示在比赛首页的 resources 列表
  public_data: "" # e.g., starting_kit, feedback_phase/input_data

# Fact sheets to add more information in the leaderboard
fact_sheet: {                   # 似乎是展示在 leaderboard 中支持用户修改的更多信息。`method_name` 该字段应与下方 `results` 平级。
    "method_name": {
        "key": "method_name",
        "type": "text",
        "title": "Method name",
        "selection": "",
        "is_required": "false",
        "is_on_leaderboard": "true"
    }
}

# Leaderboard
leaderboards:
- index: 0
  title: Results                    # leaderboard 的 title
  key: Results                      # `output.json` 中用于定位的 key
  submission_rule: "Force_Last"     # 可以去掉，默认似乎是允许展示多个结果
  columns:
      - title: Raw Score           # 原始分数列
        key: raw_score             # `output.json` 中用于定位的 key
        index: 0                   # 展示在 leaderboard 表格中的第几列
        sorting: desc              # 升序/降序排列
      - title: Average Accuracy    # 平均准确率列
        key: accuracy              # `output.json` 中用于定位的 key
        index: 1                   # 展示在 leaderboard 表格中的第几列
        sorting: desc              # 升序/降序排列
        computation: avg           # 同一用户的多个提交，按什么计算方法排序？
        computation_indexes:       # 在哪一列上计算
          - 0                      # 引用原始分数列（索引0）来计算平均值

```

File: MyTest\scoring_program\scoring_program.py
```py
import json
import os

REF_DIR = os.path.join("/app/input", "ref")
RES_DIR = os.path.join("/app/input", "res")
OUT_DIR = "/app/output"

if __name__ == "__main__":
    print("Reading prediction")

    with open(os.path.join(RES_DIR, "prediction.json"), encoding="utf-8") as file:
        res = json.load(file)
    res_data = [int(s) for s in res]

    with open(os.path.join(REF_DIR, "test_label.json"), "r", encoding="utf-8") as file:
        ref = json.load(file)
    ref_data = [int(f) for f in ref]

    print("Checking Accuracy")
    accuracy = 1.0
    score    = sum(res_data)

    SCORES = {
        "accuracy": accuracy,
        "score": score, 
    }
    print("Scores:", SCORES)

    with open(os.path.join(OUT_DIR, "scores.json"), "w") as out_file:
        out_file.write(json.dumps(SCORES))
    exit(0)
```

File: MyTest\scoring_program\metadata.yaml
```yaml
command: python scoring_program.py

```

File: MyTest\task_data\reference_data\test_label.json
```json
[
    1.0,
    2.0,
    3.0,
    4.0,
    5.0
]
```

File: MyTest\submit\prediction.json
I uploaded this json in a zip.
```json
[
    1.0,
    2.0,
    3.0,
    4.0,
    5.0
]
```

### Expected Behavior
I expect the system to properly detect the metadata file in the scoring_program directory and run the scoring program accordingly. The current error message suggests that the system is not finding the metadata file.

### Potential Issues
- Is the metadata file expected to have a specific filename or location? For example, should it be named `metadata` instead of `metadata.yaml` or be placed directly in the root of the scoring_program directory?
- Could there be an issue with the bundle structure during packaging?

### Request
Please clarify:
- What is the expected filename and location for the metadata file within the scoring_program directory?
- If the current metadata.yaml file is correctly named and located, what other factors might cause the system to not detect it?

Thank you for your help in resolving this issue!

**Comment by Didayolo** [comment]
Hi @xy3xy3,

I think you should not have `ingestion_program = ""` in your `competition.yaml`, but simply remove it like [this example](https://github.com/codalab/competition-examples/blob/master/codabench/wheat_seeds/results_submission_bundle/competition.yaml):

```yaml
tasks:
  - index: 0
    name: Wheat Seed Developement Task
    description: 'Tune models to 117 items, test against the 40 items contained in public test data'
    input_data: dev_phase/input_data/
    reference_data: dev_phase/reference_data/
    scoring_program: scoring_program/
```


Not sure it would solve the problem though. Let's investigate a bit more.
