### ISSUE TITLE
Unable to connect my remote computation worker

### ISSUE THREAD

**Issue by AtsushiHashimoto** [codalab/codabench#1817]
Hi, thank you for the nice tool.
I'm now trying to use compute_worker to support GPU in my competition.

However, as [#690 ](https://github.com/codalab/codabench/issues/690), I see the following error messages with `docker logs compute_worker` command.

```
Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
 
 -------------- compute-worker@ca7275f2a49f v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-5.15.0-86-generic-x86_64-with-glibc2.36 2025-04-10 16:39:47
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7ff1bd1d2ee0
- ** ---------- .> transport:   amqp://64d099ae-241b-4f2b-998d-97e972fbf3c4:**@www.codabench.org:5672/97904c04-45c9-4ff6-9a20-065b4f6a1515
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> compute-worker   exchange=compute-worker(direct) key=compute-worker
                

[tasks]
  . compute_worker_run

[2025-04-10 16:39:51,552: ERROR/MainProcess] consumer: Cannot connect to amqp://64d099ae-241b-4f2b-998d-97e972fbf3c4:**@www.codabench.org:5672/97904c04-45c9-4ff6-9a20-065b4f6a1515: timed out.
Trying again in 2.00 seconds..
```

my `.env` file and `docker-compose.yml` are as follows.

```
BROKER_URL=pyamqp://64d099ae-241b-4f2b-998d-97e972fbf3c4:97fead37-8306-4550-ae0b-6e9ba5c6b83c@www.codabench.org:5672/97904c04-45c9-4ff6-9a20-065b4f6a1515

HOST_DIRECTORY=/absolute/path/to/codabench
BROKER_USE_SSL=True
```
```
services:
  worker:
    image: codalab/competitions-v2-compute-worker:gpu
    container_name: compute_worker
    volumes:
      - /absolute/path/to/codabench:/codabench
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
    logging:
      options:
        max-size: 50m
        max-file: 3
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
```

Any advise to identify the cause of this error helps me greatly. In addition, is there a way to check the connection to `www.codabench.org:5672` from my PC? There is a proxy server and I'm afraid any network error exists between the server and my PC.

Currently, the following telnet command times out.
```
`% telnet 129.175.8.21 5671
Trying 129.175.8.21...
```
