### ISSUE TITLE
Stuck with "Preparing submission... this may take a few moments.."

### ISSUE THREAD

**Issue by sandywangxiao** [codalab/codabench#1832]
Hi codabench organizers,

I have started the gpu work in my own server, and use a custom docker: xiaowangsandy/biolaysum25:latest, and I have linked the queue ine the competition, and set broker_url in .env file .

When I try to submit for evaluation, it stuck with "Preparing submission... this may take a few moments.."  And it lasts for more than one hour. 

Would you help to look into this? Thank you very much!

**Comment by ObadaS** [comment]
Hello, 
Is `xiaowangsandy/biolaysum25:latest` based on `codalab/competitions-v2-compute-worker:gpu` ?

Did you also make sure to run these two commands after installing the NVIDIA toolkit ? 
```
sudo nvidia-ctk runtime configure --runtime=docker
sudo systemctl restart docker
```

**Comment by sandywangxiao** [comment]
No,  my dockerfile is:

FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install python 3.9
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository universe && \
    apt update && \
    apt install -y python3.9 python3.9-venv python3.9-dev curl && \
    ln -sf /usr/bin/python3.9 /usr/bin/python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install git
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Install pip
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.9

# Install dependencies
RUN python3 -m pip install pip --upgrade && \
    python3 -m pip install \
                textstat==0.7.5 \
                spacy==3.7.5 \
                numpy==1.24.1 \
                pandas==1.5.3 \
                f1chexbert==0.0.2 \
                radgraph==0.1.17 \
                bert-score==0.3.13 \
                nltk==3.9.1 \
                transformers==4.49.0 \
                sentence-transformers==4.0.2 \
                evaluate==0.4.3 \
                rouge-score==0.1.2 \
                lens-metric==0.2.0 &&\
                rm -rf ~/.cache/pip

RUN python3 -m spacy download en
RUN git clone https://github.com/yuh-zha/AlignScore.git
RUN git clone https://github.com/tingofurro/summac.git

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

**Comment by sandywangxiao** [comment]
hi, I have replaced it, my dockerfile-compose.yml is:
services:
    worker:
        image: xiaowangsandy/biolaysum25:latest
        container_name: compute_worker
        tty: true
        volumes:
            - .:/app/codabench
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - .env
        restart: unless-stopped
        logging:
            options:
                max-size: 50m
                max-file: 3
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
~

**Comment by ObadaS** [comment]
From what you pasted, it seems like you didn't replace the image in the `docker-compose.yml`


This line
```yml
image: xiaowangsandy/biolaysum25:latest
```

Should be 
```yml
image: codalab/competitions-v2-compute-worker:gpu
```




So your file should look like the one in the [wiki](https://github.com/codalab/codabench/wiki/Compute-Worker-Management---Setup#start-gpu-worker)
```yml
services:
    worker:
        image: codalab/competitions-v2-compute-worker:gpu
        container_name: compute_worker
        volumes:
            - /codabench:/codabench
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - .env
        restart: unless-stopped
        logging:
            options:
                max-size: 50m
                max-file: 3
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
```
