### ISSUE TITLE
My Submission is Finished, I publish it to Leaderboard, Entry is visible but Metrics are "n/a"

### ISSUE THREAD

**Issue by george200150** [codalab/codabench#1859]
The scores are successfully written in the "scoring_result.zip" downloaded from the "Output from scoring step" in a file called "scores.txt", but they are not updated on the leaderboard.

**Comment by Didayolo** [comment]
Hi @george200150,

To help you debug this, please share:
- The URL of the competition (it does not need to be public)
- The content of `scores.txt`
- The `competition.yaml` file from the bundle (specifically the definition of the leaderboard)
- Any other relevant information

**Comment by george200150** [comment]
Hello @Didayolo,

Here are the links and files you requested:
- URL: https://www.codabench.org/competitions/8431/?secret_key=3ec88f4e-99f6-41c0-9960-9ec7d4c94e48
- Scores.txt:
```
PSNR:27.194576
SSIM:0.812010
LPIPS:0.275236
ExtraRuntime:-1.000000
ExtraPlatform:-1
ExtraData:-1
```
- leaderboard from competition.yaml:
```
leaderboard:
  columns:
    ExtraData:
      label: Extra Data [1] / No Extra Data [0]
      leaderboard: &id001
        label: SingleImageMotionDeblurring
        rank: 1
      rank: 6
      sort: asc
    ExtraPlatform:
      label: CPU [1]/ GPU [0]
      leaderboard: *id001
      rank: 5
      sort: desc
    ExtraRuntime:
      label: Runtime per image [s]
      leaderboard: *id001
      rank: 4
      sort: asc
    LPIPS:
      label: LPIPS
      leaderboard: *id001
      rank: 3
      sort: asc
    PSNR:
      label: PSNR
      leaderboard: *id001
      rank: 1
      sort: desc
    SSIM:
      label: SSIM
      leaderboard: *id001
      rank: 2
      sort: desc
  leaderboards:
    SingleImageMotionDeblurring: *id001
```

First, the competition has been successfully set up on CodaLab. Results are correctly displayed in the UI there.
However, after the transition to CodaBenchmark, several other problems (python version in default image; import errors)  arised that we managed to fix.

**Comment by Didayolo** [comment]
Hi @george200150,

I am going to investigate the problem.

About versions and docker image: you can easily set what was the previous default docker image. Just open the editor (or `competition.yaml`) and set the competition docker image to `codalab/codalab-legacy:py37`.

I can see that you are installing packages in the scoring program - this is not adviced, it is more efficient and safe to simply have the right docker environment.

**Comment by Didayolo** [comment]
I tried to sanitize the leaderboard definition, but the problem remains:

```python
leaderboard:
  leaderboards:
    SingleImageMotionDeblurring: &id001
      label: SingleImageMotionDeblurring
      rank: 1
  columns:
    ExtraData:
      label: Extra Data [1] / No Extra Data [0]
      leaderboard: *id001
      rank: 1
      sort: asc
    ExtraPlatform:
      label: CPU [1]/ GPU [0]
      leaderboard: *id001
      rank: 2
      sort: desc
    ExtraRuntime:
      label: Runtime per image [s]
      leaderboard: *id001
      rank: 3
      sort: asc
    LPIPS:
      label: LPIPS
      leaderboard: *id001
      rank: 4
      sort: asc
    PSNR:
      label: PSNR
      leaderboard: *id001
      rank: 5
      sort: desc
    SSIM:
      label: SSIM
      leaderboard: *id001
      rank: 6
      sort: desc
```

**Comment by Didayolo** [comment]
@george200150 I found the source of the problem.

The YAML loading of `scores.txt`, found here:
https://github.com/codalab/codabench/blob/0108a9f9abeb4e4397f76cb1fec595c482893523/compute_worker/compute_worker.py#L901

Does not work well with the format of your `scores.txt` file. Your format is **not** legal YAML.
Indeed, in your file, there is no space between the keys and the values:

```yaml
PSNR:27.194576
SSIM:0.812010
LPIPS:0.275236
...
```

Instead of:

```yaml
PSNR: 27.194576
SSIM: 0.812010
LPIPS: 0.275236
...
```

I am not sure why it worked on CodaLab and not on Codabench, maybe the YAML loader used was different on CodaLab.

The easiest fix is to update the scoring program. Replace the last part (from line 166, writing of `scores.txt`) by:

```python
with open(os.path.join(output_dir, 'scores.txt'), 'w') as output_file:
    output_file.write("PSNR: %f\n"        % psnr)
    output_file.write("SSIM: %f\n"        % mssim)
    output_file.write("LPIPS: %f\n"       % lpips)
    output_file.write("ExtraRuntime: %f\n"% runtime)
    output_file.write("ExtraPlatform: %d\n"% cpu)
    output_file.write("ExtraData: %d\n"   % data)
```
