### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/codabench/tmpc96ht6fk/output/metadata'

### ISSUE THREAD

**Issue by wasalm** [codalab/codabench#1872]
I'm trying to run the Yellow world example on a self hosted instance of codabench.
But when I am running the example submission using competitions-v2-compute-worker I get the following error:
  
  Traceback (most recent call last):
  compute_worker  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
  compute_worker  |     R = retval = fun(*args, **kwargs)
  compute_worker  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
  compute_worker  |     return self.run(*args, **kwargs)
  compute_worker  |   File "/compute_worker.py", line 116, in run_wrapper
  compute_worker  |     run.push_output()
  compute_worker  |   File "/compute_worker.py", line 939, in push_output
  compute_worker  |     with open(metadata_path, 'w') as f:
  compute_worker  | FileNotFoundError: [Errno 2] No such file or directory: '/codabench/tmpc96ht6fk/output/metadata'

What am I doing wrong? I thought you can migrate any codalab competition to codabench.

**Comment by wasalm** [comment]
Hereby the full logs

[log.txt](https://github.com/user-attachments/files/20677381/log.txt)

**Comment by ObadaS** [comment]
Hello, I see on your other post that you have your own Codabench instance. Are you on the Develop or Master branch ?

We recently updated the compute worker code, but it brought some problems. The code is up-to-date on the develop branch but still stable on the master branch.

For now, you can change the `docker-compose.yml` file to fix the CPU worker version to `codalab/competitions-v2-compute-worker:cpu1.1`

If you are using the worker included in the docker-compose.yml file of the instance, you will have to change this : 
```yaml
  compute_worker:
    command: bash -c "watchmedo auto-restart -p '*.py' --recursive -- celery -A compute_worker worker -l info -Q compute-worker -n compute-worker@%n"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.compute_worker
    depends_on:
      - django
      - rabbit
    volumes:
      - ./compute_worker:/app
      - ${HOST_DIRECTORY:-/tmp/codabench}:/codabench
      # Actual connection back to docker parent to run things
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      - BROKER_URL=pyamqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}//
      # Make the worker leave behind the submission so we can examine it
      - CODALAB_IGNORE_CLEANUP_STEP=1
    logging:
      options:
        max-size: "20m"
        max-file: "5"
```

to : 

```yaml
  compute_worker:
    command: bash -c "watchmedo auto-restart -p '*.py' --recursive -- celery -A compute_worker worker -l info -Q compute-worker -n compute-worker@%n"
    working_dir: /app
    image: codalab/competitions-v2-compute-worker:cpu1.1
    depends_on:
      - django
      - rabbit
    volumes:
      - ./compute_worker:/app
      - ${HOST_DIRECTORY:-/tmp/codabench}:/codabench
      # Actual connection back to docker parent to run things
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      - BROKER_URL=pyamqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}//
      # Make the worker leave behind the submission so we can examine it
      - CODALAB_IGNORE_CLEANUP_STEP=1
    logging:
      options:
        max-size: "20m"
        max-file: "5"
```
