### ISSUE TITLE
v1 competition unpacker not creating computation columns

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#368]
I have a V1/V2 challenge with multiple tasks. The final rank of a participant is computed regarding its average score on all tasks. 

It works on Codalab V1:

![ave_score_1](https://user-images.githubusercontent.com/11784999/75696776-65c8a500-5cac-11ea-8241-1ed13b617a01.png)

But the exact same bundle and submission on Codalab V2 gives:

![ave_score_2](https://user-images.githubusercontent.com/11784999/75696778-66613b80-5cac-11ea-8ce4-8bef607053e8.png)

Here is the YAML configuration of the leaderboard:

```
leaderboard:
  columns:
    auc_classification:
      label: Classification (AUC ROC)
      leaderboard: &id001
        label: RESULTS
        rank: 1
      rank: 2
      sort: desc
    acc_selection:
      label: Feature Selection (accuracy)
      leaderboard: *id001
      rank: 3
      sort: desc
    acc_causality:
      label: Causal Inference (accuracy)
      leaderboard: *id001
      rank: 4
      sort: desc
    ave_score:
      label: < Rank >
      leaderboard: *id001
      rank: 1
      sort: asc
      computed:
        operation: Avg
        fields: auc_classification, acc_selection, acc_causality
  leaderboards:
    RESULTS: *id001
```
