### ISSUE TITLE
V1.5 compatibility - Unsupported features 

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#723]
This issue regroups several reported issue of compatibility and missing features with V1.5 (CodaLab Competitions).

# My submissions

- [x] Show the submission score
Solved by: #877 
- [x] Submissions left: #1015
Solved by: #1094 

# Leaderboard

### Set number of digits/decimals shown

- [x] Leaderboard: limit/specify significant digits from leaderboard's level, For exmaple in V1, https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard, numeric_format is used
Solved by: #834 

### Computation columns

- [x]  #368

Linked to #406 and #851

I have a V1/V2 challenge with multiple tasks. The final rank of a participant is computed regarding its average score on all tasks.  

It works on Codalab V1:

![ave_score_1](https://user-images.githubusercontent.com/11784999/75696776-65c8a500-5cac-11ea-8241-1ed13b617a01.png)

But the exact same bundle and submission on Codalab V2 gives:

![ave_score_2](https://user-images.githubusercontent.com/11784999/75696778-66613b80-5cac-11ea-8ce4-8bef607053e8.png)

Here is the YAML configuration of the leaderboard:

```
leaderboard:
  columns:
    auc_classification:
      label: Classification (AUC ROC)
      leaderboard: &id001
        label: RESULTS
        rank: 1
      rank: 2
      sort: desc
    acc_selection:
      label: Feature Selection (accuracy)
      leaderboard: *id001
      rank: 3
      sort: desc
    acc_causality:
      label: Causal Inference (accuracy)
      leaderboard: *id001
      rank: 4
      sort: desc
    ave_score:
      label: < Rank >
      leaderboard: *id001
      rank: 1
      sort: asc
      computed:
        operation: Avg
        fields: auc_classification, acc_selection, acc_causality
  leaderboards:
    RESULTS: *id001
```

# Download buttons, HTML files

Related:

- [x] #764
Solved by: 
#944 
#970 

### Public data and starting kit

- [x] #277 (taken care by #764)
Solved by: #970 

In V1, after uploading the bundle, it automatically adds "Starting Kit" and "Public data" to the Files tab:

![participate1](https://user-images.githubusercontent.com/11784999/71149436-d6742f80-222e-11ea-8f68-4cf24579f1d4.png)

With the exact same bundle in V2, it doesn't:

![participate2](https://user-images.githubusercontent.com/11784999/71149442-d7a55c80-222e-11ea-9d77-6dc3721b7b14.png)

[Example bundle](https://drive.google.com/open?id=1fPiNkU-tn-2awkPGWsADY4yuV63QZLSU).

### HTML documentation not interpreted

This issue is not specifically related to v1 bundles, it also happen with v2 bundle. However we can consider it a v1 compatibility issue because all v1 bundles use HTML, while you can use Markdown in v2 bundles.

- [x] #836 
Partially solved by #878 
Fully solved by #1090
