### ISSUE TITLE
v15 bundle error: "Leaderboards require at least 1 column"

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#831]
Here is the leaderboard part of the `competition.yaml` of a v15 bundle that works on CodaLab:

```yaml
# Leaderboard
leaderboard:
  leaderboards:
    Score: &id001
        label: Results
        rank: 1
  columns:
    score:
      label: Score
      leaderboard: *id001
      rank: 1
      sort: desc
    training_duration:
      label: Training time
      leaderboard: *id001
      rank: 2
      sort: asc
    duration:
      label: Scoring time
      leaderboard: *id001
      rank: 3
      sort: asc
```

The bundle unpacking returns the following error:

```

Creation failed

columns: Leaderboards require at least 1 column

```

The error is raised here in the code (https://github.com/codalab/codabench/blob/develop/src/apps/api/serializers/leaderboards.py) :

```python
    def validate_columns(self, columns):
        if not columns:
            raise serializers.ValidationError("Leaderboards require at least 1 column")
```
